// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFOeWPQWq78rZLCsE4YE4VIfIHyc8FpE',
    appId: '1:21209372993:web:d6be0ebe7ce131240129c0',
    messagingSenderId: '21209372993',
    projectId: 'onlynews-f56e4',
    authDomain: 'onlynews-f56e4.firebaseapp.com',
    storageBucket: 'onlynews-f56e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvu_MrFVVvWKQxteZY-vTLVfwtW7RyVvg',
    appId: '1:21209372993:android:602c84c7c0d1633a0129c0',
    messagingSenderId: '21209372993',
    projectId: 'onlynews-f56e4',
    storageBucket: 'onlynews-f56e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSDxXvmpJf737doTzWtO0zn_GGb8EFWU',
    appId: '1:21209372993:ios:26d570f8fc6333290129c0',
    messagingSenderId: '21209372993',
    projectId: 'onlynews-f56e4',
    storageBucket: 'onlynews-f56e4.appspot.com',
    iosBundleId: 'com.example.onlynews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSDxXvmpJf737doTzWtO0zn_GGb8EFWU',
    appId: '1:21209372993:ios:10bfb9288aed1fe70129c0',
    messagingSenderId: '21209372993',
    projectId: 'onlynews-f56e4',
    storageBucket: 'onlynews-f56e4.appspot.com',
    iosBundleId: 'com.example.onlynews.RunnerTests',
  );
}
